pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh ' mvn -f my-app/pom.xml -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f my-app/pom.xml test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.txt'
                }
            }
        }
    }
}