pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') { 
            steps {
                sh ' mvn -f my-app/pom.xml -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f my-app/pom.xml test'
            }
            post {
                always {
                    junit '**/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './my-app/scripts/deliver.sh' 
            }
        }
    }
}